### ISSUE TITLE
leerer Screen und Profildaten wurden nicht übernommen

### ISSUE THREAD

**Issue by joerglohrer** [rpi-virtuell/rw-distributed-profile-client#7]
Ich habe "joerglohrer" eingeladen. Der Benutzer wurde angelegt. Allerdings ohne mailadresse und ohne die Daten von reliwerk.de zu holen.

**Comment by staude** [comment]
Was meinst du mit eingeladen und auf welchem System? Am besten URL schicken.
Das holen der Daten geschieht bei der ersten(!) Anmeldung des Users auf einem drittsystem. Hat der User sich schon angemeldet?

**Comment by joerglohrer** [comment]
Hier eingetragen:  ![Screenshot](http://i.imgur.com/dhurZim.png)

**Comment by staude** [comment]
Fehlerhafte Konfiguration.
